Ext.define("SMSWeb.store.print.BarCodePrintStore",{
	extend:'Ext.data.Store',
	alias:'widget.BarCodePrintStore',
	model:'SMSWeb.model.print.BarCodePrintModel',
	remoteSort:false,
	pageSize:25,
	proxy:{
		type:'ajax',
		url:'main/mm/getBarCodeList',
		reader:{
			type:'json',
			root:'content',
			totalProperty :'totalElements'
		},
		writer:{
			type:'json'
		},
		listeners:{  
	        exception:Ext.ux.DataFactory.exception
	    }
	},
	autoLoad:false
});