Ext.define("SMSWeb.store.mm.sale.Store4MaterialSJ",{
	extend:'Ext.data.Store',
	model:'SMSWeb.model.mm.base.MaterialSJModel',
	proxy:{
		type:'ajax',
		url:'main/myGoods/getMaterialSanjianItemList',
		reader:{
			type:'json'
		},
		writer:{
			type:'json'
		},
		listeners:{  
	        exception:Ext.ux.DataFactory.exception
	    }
	},
	autoLoad:false
});