Ext.define("SMSWeb.store.su.Store4SysUser",{
	extend:'Ext.data.Store',
	alias:'widget.Store4SysUser',
	id:'Store4SysUser',
	model:'SMSWeb.model.su.SysUserModel',
	pageSize:25,
	proxy:{
		type:'ajax',
		url:'core/su/getAllSysUser',
		reader:{
			type:'json',
			root:'content',
			totalProperty :'totalElements'
		},
		writer:{
			type:'json'
		},
		listeners:{  
	        exception:Ext.ux.DataFactory.exception
	    }
	},
	autoLoad:true
});