create or replace view sale_prmod_item_AMOUNT_V as 
select t."ID",/*订单行项目价格汇总 2016-05-18 add lrz*/
       t."CREATE_TIME",
       t."CREATE_USER",
       t."ROW_STATUS",
       t."UPDATE_TIME",
       t."UPDATE_USER",
       t."AMOUNT",
       t."AREA",
       t."COLOUR",
       t."COLOUR_DESC",
       t."IS_SALE",
       t."ITEM_DESC",
       t."NAME",
       t."REMARK",
       t."SERIAL_NUMBER",
       t."SPEC",
       t."STATUS",
       t."TOTAL_PRICE",
       t."TOU_YING_AREA",
       t."TYPE",
       t."UNIT",
       t."UNIT_PRICE",
       t."ZHE_KOU",
       t."ZHE_KOU_JIA",
       t."PID",
       t."IS_STANDARD",
       t."MATERIAL_HEAD_ID",
       t."MATERIAL_PROPERTY_ITEM_INFO",
       t."MY_GOODS_ID",
       t."POSEX",
       t."MAKTX",
       t."MATNR",
       t."MTART",
       t."MATERIAL_PRICE",
       t."MATERIAL_PROPERTY_ITEM_ID",
       t."SANJIAN_HEAD_ID",
       t."ORDER_CODE_POSEX",
       t."BUJIAN_ID",
       t."ORTYPE",
       t."STATE_AUDIT",
       t."ABGRU",
       a."SALE_ITEMID",
       a."PR01",
       a."PR02",
       a."PR03",
       a."PR04",
       a."PR05",
       a."ZR01",
       a."ZR02",
       a."ZR03",
       a."ZR04",
       a."ZR05"
  from sale_item t ,
   (select p.sale_itemid,
                    sum(decode(TYPE, 'PR01',p.total)) "PR01",
                    sum(decode(TYPE, 'PR02', p.total)) "PR02",
                    sum(decode(TYPE, 'PR03', p.total)) "PR03",
                    sum(decode(TYPE, 'PR04', p.total)) "PR04",
                    sum(decode(TYPE, 'PR05', p.total)) "PR05",
                    sum(decode(TYPE, 'ZR01', p.total)) "ZR01",
                    sum(decode(TYPE, 'ZR02', p.total)) "ZR02",
                    sum(decode(TYPE, 'ZR03', p.total)) "ZR03",
                    sum(decode(TYPE, 'ZR04', p.total)) "ZR04",
                    sum(decode(TYPE, 'ZR05', p.total)) "ZR05"
               from sale_item_price p
              GROUP BY p.sale_itemid) a
  where t.id=a.sale_itemid(+)
;
