Ext.define("SMSWeb.model.sale.SaleOutputModel",{
	extend:'Ext.data.Model',
	fields:[
		{name:'id'},
		{name:'createUser'},
		{name:'updateUser'},
		{name:'createTime',type:'date',dateFormat:'Y-m-d H:i:s'},
		{name:'updateTime',type:'date',dateFormat:'Y-m-d H:i:s'},
		//{name:'rowStatus'},
		{ name: 'outputTime', type: 'string' },
		{ name:'custName',type:'string'},
		{ name:'custPhone',type:'string'},
		{ name: 'sapCode', type: 'string' },
		{ name: 'orderCode', type: 'string' },
		{ name: 'posex', type: 'string' },
		{ name: 'generalSum', type: 'int' },
        { name: 'carcaseSum', type: 'int' },
        { name: 'shutterSum', type: 'int'},
        { name: 'backboardSum', type: 'int' },
        { name: 'partsSum', type: 'int' },
        { name: 'metalsSum', type: 'int' },
        { name: 'sliddoorSum', type: 'int' },
        { name: 'plasticSum', type: 'int' },
        { name: 'decorationSum', type: 'int' },
        { name: 'artizanSum', type: 'int' },
        { name: 'stagepSum', type: 'int' },
        { name: 'electricSum', type: 'int' },
        { name: 'stoneSum', type: 'int' },
        { name: 'name', type: 'string' },
        { name: 'consignee', type: 'string' },
        { name: 'consigneePhone', type: 'string' },
        { name: 'kunnr', type: 'string' },
        { name: 'kunnrName', type: 'string' },
        { name: 'total',type:'string'},
        { name: 'custAddress',type:'string'},
        { name:'productName',type:'string'}
	]
});