Ext.define("SMSWeb.model.sale.SaleModel",{
	extend:'Ext.data.Model',
	fields:[
		{name:'id'},
		{name:'createUser'},
		{name:'updateUser'},
		{name:'createTime',type:'date',dateFormat:'Y-m-d H:i:s'},
		{name:'updateTime',type:'date',dateFormat:'Y-m-d H:i:s'},
		//{name:'rowStatus'},
		{name:'posex'},
		{ name: 'matnr', type: 'string' },
		{ name: 'mtart', type: 'string' },
		{ name: 'maktx', type: 'string' },
//		{ name: 'unitPrice', type: 'float' },
//		{ name: 'zheKou', type: 'float' },
//        { name: 'zheKouJia', type: 'float' },
//        { name: 'active', type: 'bool' }
        { name: 'amount', type: 'float' },
        { name: 'touYingArea', type: 'float' },
        { name: 'totalPrice', type: 'float' },
        { name: 'status', type: 'string' },
        { name: 'materialHeadId', type: 'string' },
        { name: 'isStandard', type: 'string' },
        { name: 'materialPropertyItemInfo', type: 'string' },
        { name: 'materialPrice', type: 'float' },
        { name: 'myGoodsId', type: 'string' },
        { name: 'sanjianHeadId', type: 'string' },
        { name: 'bujianId', type: 'string' },
        { name: 'ortype', type: 'string' },
        { name: 'orderCodePosex', type: 'string' },
        { name: 'stateAudit', type: 'string' },
        { name: 'jdName', type: 'string' },
        { name: 'drawType', type: 'string' },
        { name: 'kitId', type: 'string' },
        { name: 'pdfId', type: 'string' },
        { name: 'priceId', type: 'string' },
        { name: 'saleFor', type: 'string' },
        { name: 'sapCode', type: 'string' },
        { name: 'sapCodePosex', type: 'string' },
        { name: 'zzwgfg', type: 'string' },
        { name: 'remark', type: 'string' },
        {name:'unit',type: 'string' },
        {name:'serial',type: 'string' }, //serial
        { name: 'orderEvent', type: 'string' }
	]
});