Ext.define("SMSWeb.store.sale.SaleLogisticsStore",{
	extend:'Ext.data.Store',
	alias:'widget.SaleOneCustStore',
	model:'SMSWeb.model.sale.SaleLogisticsModel',
	remoteSort:false,
	pageSize:25,
	proxy:{
		type:'ajax',
		url:'sale/log/findSaleLogisticsStoreInfo',
		reader:{
			type:'json',
			root:'content',
			totalProperty :'totalElements'
		},
		writer:{
			type:'json'
		},
		listeners:{  
	        exception:Ext.ux.DataFactory.exception
	    }
	},
	autoLoad:false
});