Ext.define("SMSWeb.store.sale.SaleOneCustStore",{
	extend:'Ext.data.Store',
	alias:'widget.SaleOneCustStore',
	model:'SMSWeb.model.sale.SaleOneCustModel',
	remoteSort:false,
	pageSize:25,
	proxy:{
		type:'ajax',
		url:'main/sale/findSaleOneCustsByPid',
		reader:{
			type:'json',
			root:'content',
			totalProperty :'totalElements'
		},
		writer:{
			type:'json'
		},
		listeners:{  
	        exception:Ext.ux.DataFactory.exception
	    }
	},
	autoLoad:false
});