package com.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ImosServerSoap", targetNamespace = "http://tempuri.org/")
public interface ImosServerSoap {

	/**
	 * 
	 * @param xmlFile
	 * @param orderId
	 * @return returns boolean
	 */
	@WebMethod(operationName = "AcceptOrder", action = "http://tempuri.org/AcceptOrder")
	@WebResult(name = "AcceptOrderResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "AcceptOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AcceptOrder")
	@ResponseWrapper(localName = "AcceptOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AcceptOrderResponse")
	public boolean acceptOrder(
			@WebParam(name = "orderId", targetNamespace = "http://tempuri.org/") String orderId,
			@WebParam(name = "xmlFile", targetNamespace = "http://tempuri.org/") String xmlFile);

}
