package com.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ImosServer service = new ImosServer();
 * ImosServerSoap portType = service.getImosServerSoap();
 * portType.acceptOrder(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ImosServer", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.16.3.219:8093/ImosServer.asmx?wsdl")
public class ImosServer extends Service {

	private final static URL IMOSSERVER_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(ImosServer.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = ImosServer.class.getResource(".");
			url = new URL(baseUrl,"http://172.16.3.219:8093/ImosServer.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.3.219:8093/ImosServer.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		IMOSSERVER_WSDL_LOCATION = url;
	}

	public ImosServer(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ImosServer() {
		super(IMOSSERVER_WSDL_LOCATION, new QName("http://tempuri.org/",
				"ImosServer"));
	}

	/**
	 * 
	 * @return returns ImosServerSoap
	 */
	@WebEndpoint(name = "ImosServerSoap")
	public ImosServerSoap getImosServerSoap() {
		return super.getPort(
				new QName("http://tempuri.org/", "ImosServerSoap"),
				ImosServerSoap.class);
	}

	/**
	 * 
	 * @return returns ImosServerSoap
	 */
	@WebEndpoint(name = "ImosServerSoap12")
	public ImosServerSoap getImosServerSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"ImosServerSoap12"), ImosServerSoap.class);
	}

}
